name: Build and release docs

on:
    push:
        branches: [main]

permissions:
  contents: read

jobs:
    build_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout 🛎️
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4 # If you're using actions/checkout since v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
              with:
                  persist-credentials: false

            - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
              with:
                  node-version: 20

            - name: Install and build the documentation🔧
              run: |
                  npm install
                  npm link
                  npm run docs:refresh

            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
              with:
                  branch: main
                  folder: docs
                  ssh-key: ${{ secrets.DEPLOY_KEY }}
