# Simple workflow for deploying static content to GitHub Pages
name: Run tests

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "tests"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version: 20
      - name: Build
        run: |
          npm install
          npm link
          npm run lint
      - name: Cache downloaded compilers
        id: solc-cache
        uses: actions/cache@v4
        with:
          path: ~/node_modules/solc-typed-ast/.compiler_cache
          key: solc-cache
      - name: Pre-download compilers from historical builds archive
        run: |
            npx sol-ast-compile --download-compilers wasm
      - name: Test
        run: |
          npm run test